mod export;

use ayuc_hir::{
    AlternateBranch, AssignOp, BinaryOp, Block, Def, Expr, ExprKind, ExternFnItem, ExternModItem,
    FnItem, IfStmt, InlineModItem, IntlSegment, Item, ItemKind, Literal, Parameter, Path, Stmt,
    StmtKind, Visibility,
};
use ayuc_id::hir::DefId;
use ayuc_lower::LoweringContext;
use ayuc_pretty::{doc::Doc, renderer::Renderer};
use ayuc_span::symbol::Symbol;

use crate::export::Export;

fn defs_to_exports<'a>(
    lcx: &'a LoweringContext,
    defs: &[DefId],
    absolute_path: &[&'a str],
) -> Vec<Export<'a>> {
    defs.iter()
        .map(|def| &lcx.items[*def])
        .filter(|i| i.vis == Visibility::Public)
        .flat_map(|i| match &i.kind {
            ItemKind::ExternFn(_) | ItemKind::ExternMod(_) => None,
            ItemKind::Fn(fun) => Some(Export::mapped(
                fun.name.as_str(),
                format!(
                    "{}{}{}",
                    absolute_path.join("."),
                    if absolute_path.is_empty() { "" } else { "." },
                    fun.name
                ),
            )),
            ItemKind::InlineMod(modu) => Some(Export::module(
                modu.name.as_str(),
                defs_to_exports(
                    lcx,
                    &modu.items,
                    &[absolute_path, &[modu.name.as_str()]].concat(),
                ),
            )),
        })
        .collect()
}

pub struct LuauCodegen;

impl LuauCodegen {
    pub fn emit(lcx: &LoweringContext) -> String {
        let mut doc = Self::lcx_to_doc(lcx);
        let mut contains_main = false;

        for (_, item) in lcx.top_items() {
            if let ItemKind::Fn(FnItem { name, .. }) = item.kind
                && name.as_str() == "main"
            {
                contains_main = true;
            }
        }

        if contains_main {
            doc = Doc::Concat(vec![
                doc,
                Doc::text("return main() -- autogenerated by ayuc"),
            ])
        } else {
            let exports = defs_to_exports(lcx, &lcx.top_level_items, &[]);

            let parts = if exports.is_empty() {
                Doc::Skip
            } else {
                let docs = exports
                    .into_iter()
                    .map(|e| Self::export_to_doc(e))
                    .enumerate()
                    .map(|(i, doc)| {
                        if i == 0 {
                            doc
                        } else {
                            Doc::concat([Doc::text(","), Doc::Hardline, doc])
                        }
                    })
                    .collect::<Vec<_>>();

                Doc::concat([Doc::Hardline, Doc::indent(Doc::concat(docs)), Doc::Hardline])
            };

            doc = Doc::Concat(vec![
                doc,
                Doc::Concat(vec![Doc::text("return {"), parts, Doc::text("}")]),
            ]);
        }

        Renderer::new().render(&doc)
    }

    fn export_to_doc(export: Export) -> Doc {
        match export {
            Export::Mapped { name, absolute } => {
                Doc::concat([Doc::text(name), Doc::text(" = "), Doc::text(&absolute)])
            }
            Export::Module { name, children } => {
                let line = if !children.is_empty() {
                    Doc::Hardline
                } else {
                    Doc::Skip
                };

                Doc::concat([
                    Doc::text(name),
                    Doc::text(" = "),
                    Doc::text("{"),
                    line.clone(),
                    Doc::indent(Doc::Concat(
                        children
                            .into_iter()
                            .map(|export| Self::export_to_doc(export))
                            .enumerate()
                            .map(|(i, doc)| {
                                if i == 0 {
                                    doc
                                } else {
                                    Doc::concat([Doc::text(","), Doc::Hardline, doc])
                                }
                            })
                            .collect(),
                    )),
                    line,
                    Doc::text("}"),
                ])
            }
        }
    }

    fn sym_of_item(item: &Item) -> Symbol {
        match &item.kind {
            ItemKind::Fn(FnItem { name: sym, .. })
            | ItemKind::ExternFn(ExternFnItem {
                name: sym,
                ffi_name: None,
                ..
            })
            | ItemKind::ExternFn(ExternFnItem {
                name: _,
                ffi_name: Some(sym),
                ..
            })
            | ItemKind::InlineMod(InlineModItem { name: sym, .. })
            | ItemKind::ExternMod(ExternModItem {
                name: sym,
                ffi_name: None,
                ..
            })
            | ItemKind::ExternMod(ExternModItem {
                name: _,
                ffi_name: Some(sym),
                ..
            }) => *sym,
        }
    }

    fn lcx_to_doc(lcx: &LoweringContext) -> Doc {
        // 1st pass: Declare all items
        let first = Doc::Concat(
            lcx.top_items()
                .iter()
                .flat_map(|(_, item)| Self::declared_item(lcx, item, false))
                .map(|doc| Doc::concat([doc, Doc::Hardline]))
                .collect(),
        );

        // 2nd pass: Define all items
        let second = Doc::Concat(
            lcx.top_items()
                .iter()
                .flat_map(|(_, item)| Self::define_item(lcx, item, &[]))
                .map(|doc| Doc::Concat(vec![doc, Doc::Hardline, Doc::Blankline]))
                .collect(),
        );

        Doc::concat([first, Doc::Blankline, second])
    }

    fn is_visible_item(lcx: &LoweringContext, item: &Item) -> bool {
        match &item.kind {
            ItemKind::ExternFn(_) | ItemKind::ExternMod(_) => false,
            ItemKind::Fn(_) => true,
            ItemKind::InlineMod(decl) => decl
                .items
                .iter()
                .map(|id| &lcx.items[*id])
                .any(|item| Self::is_visible_item(lcx, item)),
        }
    }

    fn declared_item(lcx: &LoweringContext, item: &Item, within_module: bool) -> Option<Doc> {
        match &item.kind {
            ItemKind::InlineMod(decl) => {
                let has_visible_items = Self::is_visible_item(lcx, item);

                if !has_visible_items {
                    return None;
                }

                let children = decl
                    .items
                    .iter()
                    .map(|id| &lcx.items[*id])
                    .flat_map(|item| Self::declared_item(lcx, item, true))
                    .collect::<Vec<_>>();

                Some(Doc::concat([
                    if !within_module {
                        Doc::text("local ")
                    } else {
                        Doc::Skip
                    },
                    Doc::text(format!("{} = ", decl.name)),
                    Doc::text("{"),
                    if children.is_empty() {
                        Doc::Skip
                    } else {
                        Doc::concat([
                            Doc::Hardline,
                            Doc::indent(Doc::concat(children)),
                            Doc::Hardline,
                        ])
                    },
                    Doc::text("}"),
                ]))
            }
            ItemKind::Fn(decl) => {
                (!within_module).then_some(Doc::text(format!("local {}", decl.name)))
            }
            ItemKind::ExternMod(_) | ItemKind::ExternFn(_) => None,
        }
    }

    fn define_item(lcx: &LoweringContext, item: &Item, absolute_path: &[Symbol]) -> Option<Doc> {
        match &item.kind {
            ItemKind::InlineMod(decl) => {
                let items = decl
                    .items
                    .iter()
                    .flat_map(|item| {
                        Self::define_item(
                            lcx,
                            &lcx.items[*item],
                            &[absolute_path, &[decl.name]].concat(),
                        )
                    })
                    .enumerate()
                    .map(|(i, doc)| {
                        if i != 0 {
                            Doc::concat([Doc::Hardline, Doc::Blankline, doc])
                        } else {
                            doc
                        }
                    })
                    .collect::<Vec<_>>();

                if items.is_empty() {
                    None
                } else {
                    Some(Doc::Concat(items))
                }
            }
            ItemKind::Fn(decl) => {
                let mut params = Vec::new();

                for (i, param) in decl.params.iter().enumerate() {
                    if i != 0 {
                        params.push(Doc::text(", "));
                    }

                    params.push(Self::param_to_doc(lcx, param));
                }

                Some(Doc::Concat(Vec::from([
                    Self::syms_to_doc(&[absolute_path, &[decl.name]].concat()),
                    Doc::text(" = "),
                    Doc::text("function"),
                    Doc::text("("),
                    Doc::Concat(params),
                    Doc::text(")"),
                    Doc::Hardline,
                    Doc::indent(Self::block_to_doc(lcx, &decl.block)),
                    Doc::Hardline,
                    Doc::text("end"),
                ])))
            }
            ItemKind::ExternFn(_) | ItemKind::ExternMod(_) => None,
        }
    }

    fn syms_to_doc(syms: &[Symbol]) -> Doc {
        Doc::Concat(
            syms.iter()
                .enumerate()
                .map(|(i, sym)| {
                    if i != 0 {
                        Doc::concat([Doc::text("."), Doc::text(sym.as_str())])
                    } else {
                        Doc::text(sym.as_str())
                    }
                })
                .collect(),
        )
    }

    fn param_to_doc(_lcx: &LoweringContext, param: &Parameter) -> Doc {
        Doc::text(param.name.as_str())
    }

    fn block_to_doc(lcx: &LoweringContext, block: &Block) -> Doc {
        let mut docs = Vec::new();

        for (i, stmt) in block.stmts.iter().enumerate() {
            if i != 0 {
                docs.push(Doc::StmtSep);
            }

            docs.push(Self::stmt_to_doc(lcx, stmt));
        }

        Doc::Concat(docs)
    }

    fn stmt_to_doc(lcx: &LoweringContext, stmt: &Stmt) -> Doc {
        match &stmt.kind {
            StmtKind::Break => Doc::text("break"),
            StmtKind::Loop(r#loop) => Doc::Concat(Vec::from([
                Doc::text("while true do"),
                Doc::Hardline,
                Doc::indent(Self::block_to_doc(lcx, &r#loop.block)),
                Doc::Hardline,
                Doc::text("end"),
            ])),
            StmtKind::While(r#while) => Doc::Concat(Vec::from([
                Doc::text("while "),
                Self::expr_to_doc(lcx, &r#while.expr, false),
                Doc::text(" do"),
                Doc::Hardline,
                Doc::indent(Self::block_to_doc(lcx, &r#while.block)),
                Doc::Hardline,
                Doc::text("end"),
            ])),
            StmtKind::Assign(assign) => Doc::Concat(Vec::from([
                Doc::text(Self::def_to_sym(lcx, &assign.ident).as_str()),
                Doc::text(" "),
                Doc::text(match assign.op {
                    AssignOp::Add => "+=",
                    AssignOp::Sub => "-=",
                    AssignOp::Assign => "=",
                    AssignOp::Div => "/=",
                    AssignOp::Modulus => "%=",
                    AssignOp::Mul => "*=",
                }),
                Doc::text(" "),
                Self::expr_to_doc(lcx, &assign.value, false),
            ])),
            StmtKind::Return(ret) => Doc::Concat(vec![
                Doc::text("return "),
                Self::expr_to_doc(lcx, &ret.expr, false),
            ]),
            StmtKind::Expr(expr) => Self::expr_to_doc(lcx, expr, false),
            StmtKind::If(if_stmt) => Self::if_stmt_to_doc(lcx, if_stmt, false),
            StmtKind::Let(decl) => {
                let expr_doc = Self::expr_to_doc(lcx, &decl.init, false);

                Doc::Concat(Vec::from([
                    Doc::text("local "),
                    Doc::text(decl.ident.as_str()),
                    if expr_doc.is_empty() {
                        Doc::Skip
                    } else {
                        Doc::concat([Doc::text(" = "), expr_doc])
                    },
                ]))
            }
        }
    }

    fn if_stmt_to_doc(lcx: &LoweringContext, if_stmt: &IfStmt, loose_end: bool) -> Doc {
        let IfStmt {
            expr,
            block,
            alternate,
        } = if_stmt;

        let mut parts = Vec::from([
            Doc::text("if "),
            Self::expr_to_doc(lcx, expr, false),
            Doc::text(" then"),
            Doc::Hardline,
            Doc::indent(Self::block_to_doc(lcx, block)),
            Doc::Hardline,
        ]);

        match alternate {
            Some(AlternateBranch::Another(if_stmt)) => {
                parts.extend([Doc::text("else"), Self::if_stmt_to_doc(lcx, if_stmt, true)]);
            }
            Some(AlternateBranch::Final(block)) => {
                parts.extend([
                    Doc::text("else"),
                    Doc::Hardline,
                    Doc::indent(Self::block_to_doc(lcx, block)),
                    Doc::Hardline,
                ]);
            }
            None => {}
        }

        if !loose_end {
            parts.push(Doc::text("end"));
        }

        Doc::Concat(parts)
    }

    fn expr_to_doc(lcx: &LoweringContext, expr: &Expr, wrap_expr: bool) -> Doc {
        match &expr.kind {
            ExprKind::Tuple(inner) => {
                let all = Doc::Concat(
                    inner
                        .iter()
                        .map(|expr| Self::expr_to_doc(lcx, expr, true))
                        .enumerate()
                        .map(|(i, doc)| {
                            if i == 0 {
                                doc
                            } else {
                                Doc::concat([Doc::text(", "), doc])
                            }
                        })
                        .collect(),
                );

                if wrap_expr {
                    // This only applies to tuples that are inside other exressions.
                    // Lua doesn't allow ((number, number), number), so we convert it to ({number}, number).

                    Doc::concat([Doc::text("{"), all, Doc::text("}")])
                } else {
                    all
                }
            }
            ExprKind::Lit(lit) => match lit {
                Literal::Bool(value) => Doc::text(if *value { "true" } else { "false" }),
                Literal::Integer(value) => Doc::text(value.to_string()),
                Literal::Str(str) => Doc::Concat(Vec::from([
                    Doc::text("\""),
                    Doc::text(str.as_str()),
                    Doc::text("\""),
                ])),
                Literal::InterpolatedStr(segments) => Doc::Concat(Vec::from([
                    Doc::text("`"),
                    Doc::Concat(
                        segments
                            .iter()
                            .map(|segment| match segment {
                                IntlSegment::Text(text) => Doc::text(
                                    text.as_str().replace("{{", "\\{").replace("}}", "\\}"),
                                ),
                                IntlSegment::Var(def) => Doc::Concat(Vec::from([
                                    Doc::text("{"),
                                    Doc::text(Self::def_to_sym(lcx, def).as_str()),
                                    Doc::text("}"),
                                ])),
                            })
                            .collect(),
                    ),
                    Doc::text("`"),
                ])),
            },
            ExprKind::Binary(bin) => {
                let doc = Doc::Concat(Vec::from([
                    Self::expr_to_doc(lcx, &bin.left, true),
                    Doc::text(" "),
                    Doc::text(match bin.operator {
                        BinaryOp::Add => "+",
                        BinaryOp::Gt => ">",
                        BinaryOp::EqualsEquals => "==",
                        BinaryOp::GtOrEqual => ">=",
                        BinaryOp::Lt => "<",
                        BinaryOp::LtOrEqual => "<=",
                        BinaryOp::Minus => "-",
                        BinaryOp::NotEquals => "~=",
                        BinaryOp::Div => "/",
                        BinaryOp::Modulus => "%",
                        BinaryOp::Mul => "*",
                    }),
                    Doc::text(" "),
                    Self::expr_to_doc(lcx, &bin.right, true),
                ]));

                if wrap_expr {
                    Doc::concat([Doc::text("("), doc, Doc::text(")")])
                } else {
                    doc
                }
            }
            ExprKind::Call(call) => Doc::Concat(Vec::from([
                Self::expr_to_doc(lcx, &call.callee, true),
                Doc::text("("),
                Doc::Concat(
                    call.args
                        .iter()
                        .enumerate()
                        .flat_map(|(i, expr)| {
                            if i != 0 {
                                Vec::from([Doc::text(", "), Self::expr_to_doc(lcx, expr, false)])
                            } else {
                                Vec::from([Self::expr_to_doc(lcx, expr, false)])
                            }
                        })
                        .collect(),
                ),
                Doc::text(")"),
            ])),
            ExprKind::Parenthesized(expr) => Doc::concat([
                Doc::text("("),
                Self::expr_to_doc(lcx, expr, false),
                Doc::text(")"),
            ]),
            ExprKind::Path(path) => Self::path_to_doc(lcx, path),
        }
    }

    fn path_to_doc(lcx: &LoweringContext, path: &Path) -> Doc {
        let target_is_extern = Self::def_is_extern(lcx, &path.target);

        if path.segments.len() == 1 {
            return Doc::text(Self::def_to_sym(lcx, &path.target).as_str());
        }

        Doc::Concat(
            path.segments
                .iter()
                .filter(|def| {
                    if target_is_extern {
                        Self::def_is_extern(lcx, def)
                    } else {
                        true
                    }
                })
                .map(|def| Self::def_to_doc(lcx, def))
                .enumerate()
                .map(|(i, doc)| {
                    if i != 0 {
                        Doc::Concat(vec![Doc::text("."), doc])
                    } else {
                        doc
                    }
                })
                .collect(),
        )
    }

    fn def_is_extern(lcx: &LoweringContext, def: &Def) -> bool {
        if let Def::Def(id) = def {
            match &lcx.items[*id].kind {
                ItemKind::ExternFn(_) | ItemKind::ExternMod(_) => true,
                ItemKind::Fn(_) | ItemKind::InlineMod(_) => false,
            }
        } else {
            false
        }
    }

    fn def_to_sym(lcx: &LoweringContext, def: &Def) -> Symbol {
        match def {
            Def::Def(def) => Self::sym_of_item(&lcx.items[*def]),
            Def::Local(local) => lcx.locals[*local].name,
        }
    }

    fn def_to_doc(lcx: &LoweringContext, def: &Def) -> Doc {
        Doc::text(Self::def_to_sym(lcx, def).as_str())
    }
}
