use ayuc_hir::{
    AlternateBranch, AssignOp, BinaryOp, Block, Def, Expr, ExprKind, ExternFnItem, ExternModItem,
    FnItem, IfStmt, InlineModItem, IntlSegment, Item, ItemKind, Literal, Parameter, Path, Stmt,
    StmtKind, Visibility,
};
use ayuc_lower::LoweringContext;
use ayuc_pretty::{doc::Doc, renderer::Renderer};
use ayuc_span::symbol::Symbol;

pub struct LuauCodegen;

impl LuauCodegen {
    pub fn emit(lcx: &LoweringContext) -> String {
        let mut doc = Self::lcx_to_doc(lcx);
        let mut contains_main = false;

        for (_, item) in lcx.top_items() {
            if let ItemKind::Fn(FnItem { name, .. }) = item.kind
                && name.as_str() == "main"
            {
                contains_main = true;
            }
        }

        if contains_main {
            doc = Doc::Concat(vec![
                doc,
                Doc::text("return main() -- autogenerated by ayuc"),
            ])
        } else {
            let export_table: Vec<Symbol> = lcx
                .top_items()
                .iter()
                .filter(|(_, item)| item.vis != Visibility::Private)
                .filter_map(|(_, item)| match &item.kind {
                    ItemKind::Fn(fun) => Some(fun.name),
                    ItemKind::InlineMod(decl) => Some(decl.name),
                    ItemKind::ExternFn(_) | ItemKind::ExternMod(_) => None,
                })
                .collect();

            let parts = if export_table.is_empty() {
                vec![]
            } else {
                let mut doc_parts = Vec::with_capacity(export_table.len() * 3);

                for (i, sym) in export_table.into_iter().enumerate() {
                    if i > 0 {
                        doc_parts.push(Doc::text(","));
                        doc_parts.push(Doc::Hardline);
                    }
                    doc_parts.push(Doc::text(format!("{sym} = {sym}")));
                }

                vec![
                    Doc::Hardline,
                    Doc::Indent(Box::new(Doc::Concat(doc_parts))),
                    Doc::Hardline,
                ]
            };

            doc = Doc::Concat(vec![
                doc,
                Doc::Concat(vec![
                    Doc::text("return {"),
                    Doc::Concat(parts),
                    Doc::text("}"),
                ]),
            ]);
        }

        Renderer::new().render(doc)
    }

    fn sym_of_item(item: &Item) -> Symbol {
        match &item.kind {
            ItemKind::Fn(FnItem { name: sym, .. })
            | ItemKind::ExternFn(ExternFnItem {
                name: sym,
                ffi_name: None,
                ..
            })
            | ItemKind::ExternFn(ExternFnItem {
                name: _,
                ffi_name: Some(sym),
                ..
            })
            | ItemKind::InlineMod(InlineModItem { name: sym, .. })
            | ItemKind::ExternMod(ExternModItem {
                name: sym,
                ffi_name: None,
                ..
            })
            | ItemKind::ExternMod(ExternModItem {
                name: _,
                ffi_name: Some(sym),
                ..
            }) => *sym,
        }
    }

    fn lcx_to_doc(lcx: &LoweringContext) -> Doc {
        Doc::Concat(
            lcx.top_items()
                .iter()
                .flat_map(|(_, item)| Self::item_to_doc(lcx, item, true))
                .map(|doc| Doc::Concat(vec![doc, Doc::Hardline, Doc::Blankline]))
                .collect(),
        )
    }

    fn item_to_doc(lcx: &LoweringContext, item: &Item, with_name: bool) -> Option<Doc> {
        match &item.kind {
            ItemKind::InlineMod(decl) => {
                let items = decl
                    .items
                    .iter()
                    .flat_map(|item| {
                        Self::item_to_doc(lcx, &lcx.items[*item], false)
                            .map(|doc| (&lcx.items[*item], doc))
                    })
                    .map(|(item, doc)| {
                        Doc::Concat(vec![
                            Doc::Hardline,
                            Doc::text(Self::sym_of_item(item).as_str()),
                            Doc::text(" = "),
                            doc,
                            Doc::text(","),
                        ])
                    })
                    .collect::<Vec<_>>();

                if items.is_empty() {
                    None
                } else {
                    Some(Doc::Concat(vec![
                        Doc::text("local "),
                        Doc::text(decl.name.as_str()),
                        Doc::text(" = "),
                        Doc::Concat(vec![
                            Doc::text("{"),
                            Doc::Indent(Box::new(Doc::Concat(items))),
                            Doc::Hardline,
                            Doc::text("}"),
                        ]),
                    ]))
                }
            }
            ItemKind::Fn(decl) => {
                let mut params = Vec::new();

                for (i, param) in decl.params.iter().enumerate() {
                    if i != 0 {
                        params.push(Doc::text(", "));
                    }

                    params.push(Self::param_to_doc(lcx, param));
                }

                Some(Doc::Concat(Vec::from([
                    Doc::text("function "),
                    if with_name {
                        Doc::text(decl.name.as_str())
                    } else {
                        Doc::Skip
                    },
                    Doc::text("("),
                    Doc::Concat(params),
                    Doc::text(")"),
                    Doc::Hardline,
                    Doc::indent(Self::block_to_doc(lcx, &decl.block)),
                    Doc::Hardline,
                    Doc::text("end"),
                ])))
            }
            ItemKind::ExternFn(_) | ItemKind::ExternMod(_) => None,
        }
    }

    fn param_to_doc(_lcx: &LoweringContext, param: &Parameter) -> Doc {
        Doc::text(param.name.as_str())
    }

    fn block_to_doc(lcx: &LoweringContext, block: &Block) -> Doc {
        let mut docs = Vec::new();

        for (i, stmt) in block.stmts.iter().enumerate() {
            if i != 0 {
                docs.push(Doc::StmtSep);
            }

            docs.push(Self::stmt_to_doc(lcx, stmt));
        }

        Doc::Concat(docs)
    }

    fn stmt_to_doc(lcx: &LoweringContext, stmt: &Stmt) -> Doc {
        match &stmt.kind {
            StmtKind::Break => Doc::text("break"),
            StmtKind::Loop(r#loop) => Doc::Concat(Vec::from([
                Doc::text("while true do"),
                Doc::Hardline,
                Doc::indent(Self::block_to_doc(lcx, &r#loop.block)),
                Doc::Hardline,
                Doc::text("end"),
            ])),
            StmtKind::While(r#while) => Doc::Concat(Vec::from([
                Doc::text("while "),
                Self::expr_to_doc(lcx, &r#while.expr),
                Doc::text(" do"),
                Doc::Hardline,
                Doc::indent(Self::block_to_doc(lcx, &r#while.block)),
                Doc::Hardline,
                Doc::text("end"),
            ])),
            StmtKind::Assign(assign) => Doc::Concat(Vec::from([
                Doc::text(Self::def_to_sym(lcx, &assign.ident).as_str()),
                Doc::text(" "),
                Doc::text(match assign.op {
                    AssignOp::Add => "+=",
                    AssignOp::Sub => "-=",
                    AssignOp::Assign => "=",
                }),
                Doc::text(" "),
                Self::expr_to_doc(lcx, &assign.value),
            ])),
            StmtKind::Return(ret) => Doc::Concat(vec![
                Doc::text("return"),
                ret.expr
                    .as_ref()
                    .map(|expr| {
                        Doc::Concat(Vec::from([Doc::text(" "), Self::expr_to_doc(lcx, expr)]))
                    })
                    .unwrap_or(Doc::Concat(Vec::new())),
            ]),
            StmtKind::Expr(expr) => Self::expr_to_doc(lcx, expr),
            StmtKind::If(if_stmt) => Self::if_stmt_to_doc(lcx, if_stmt, false),
            StmtKind::Let(decl) => Doc::Concat(Vec::from([
                Doc::text("local "),
                Doc::text(decl.ident.as_str()),
                Doc::text(" = "),
                Self::expr_to_doc(lcx, &decl.init),
            ])),
        }
    }

    fn if_stmt_to_doc(lcx: &LoweringContext, if_stmt: &IfStmt, loose_end: bool) -> Doc {
        let IfStmt {
            expr,
            block,
            alternate,
        } = if_stmt;

        let mut parts = Vec::from([
            Doc::text("if "),
            Self::expr_to_doc(lcx, expr),
            Doc::text(" then"),
            Doc::Hardline,
            Doc::indent(Self::block_to_doc(lcx, block)),
            Doc::Hardline,
        ]);

        match alternate {
            Some(AlternateBranch::Another(if_stmt)) => {
                parts.extend([Doc::text("else"), Self::if_stmt_to_doc(lcx, if_stmt, true)]);
            }
            Some(AlternateBranch::Final(block)) => {
                parts.extend([
                    Doc::text("else"),
                    Doc::Hardline,
                    Doc::indent(Self::block_to_doc(lcx, block)),
                    Doc::Hardline,
                ]);
            }
            None => {}
        }

        if !loose_end {
            parts.push(Doc::text("end"));
        }

        Doc::Concat(parts)
    }

    fn expr_to_doc(lcx: &LoweringContext, expr: &Expr) -> Doc {
        match &expr.kind {
            ExprKind::Lit(lit) => match lit {
                Literal::Bool(value) => Doc::text(if *value { "true" } else { "false" }),
                Literal::Integer(value) => Doc::text(value.to_string()),
                Literal::Str(str) => Doc::Concat(Vec::from([
                    Doc::text("\""),
                    Doc::text(str.as_str()),
                    Doc::text("\""),
                ])),
                Literal::InterpolatedStr(segments) => Doc::Concat(Vec::from([
                    Doc::text("`"),
                    Doc::Concat(
                        segments
                            .iter()
                            .map(|segment| match segment {
                                IntlSegment::Text(text) => Doc::text(
                                    text.as_str().replace("{{", "\\{").replace("}}", "\\}"),
                                ),
                                IntlSegment::Var(def) => Doc::Concat(Vec::from([
                                    Doc::text("{"),
                                    Doc::text(Self::def_to_sym(lcx, def).as_str()),
                                    Doc::text("}"),
                                ])),
                            })
                            .collect(),
                    ),
                    Doc::text("`"),
                ])),
            },
            ExprKind::Binary(bin) => Doc::Concat(Vec::from([
                Self::expr_to_doc(lcx, &bin.left),
                Doc::text(" "),
                Doc::text(match bin.operator {
                    BinaryOp::Add => "+",
                    BinaryOp::Gt => ">",
                    BinaryOp::EqualsEquals => "==",
                    BinaryOp::GtOrEqual => ">=",
                    BinaryOp::Lt => "<",
                    BinaryOp::LtOrEqual => "<=",
                    BinaryOp::Minus => "-",
                    BinaryOp::NotEquals => "~=",
                }),
                Doc::text(" "),
                Self::expr_to_doc(lcx, &bin.right),
            ])),
            ExprKind::Call(call) => Doc::Concat(Vec::from([
                Self::expr_to_doc(lcx, &call.callee),
                Doc::text("("),
                Doc::Concat(
                    call.args
                        .iter()
                        .enumerate()
                        .flat_map(|(i, expr)| {
                            if i != 0 {
                                Vec::from([Doc::text(", "), Self::expr_to_doc(lcx, expr)])
                            } else {
                                Vec::from([Self::expr_to_doc(lcx, expr)])
                            }
                        })
                        .collect(),
                ),
                Doc::text(")"),
            ])),
            ExprKind::Path(path) => Self::path_to_doc(lcx, path),
        }
    }

    fn path_to_doc(lcx: &LoweringContext, path: &Path) -> Doc {
        let target_is_extern = Self::def_is_extern(lcx, &path.target);

        if path.segments.len() == 1 {
            return Doc::text(Self::def_to_sym(lcx, &path.target).as_str());
        }

        Doc::Concat(
            path.segments
                .iter()
                .filter(|def| {
                    if target_is_extern {
                        Self::def_is_extern(lcx, def)
                    } else {
                        true
                    }
                })
                .map(|def| Self::def_to_doc(lcx, def))
                .enumerate()
                .map(|(i, doc)| {
                    if i != 0 {
                        Doc::Concat(vec![Doc::text("."), doc])
                    } else {
                        doc
                    }
                })
                .collect(),
        )
    }

    fn def_is_extern(lcx: &LoweringContext, def: &Def) -> bool {
        if let Def::Def(id) = def {
            match &lcx.items[*id].kind {
                ItemKind::ExternFn(_) | ItemKind::ExternMod(_) => true,
                ItemKind::Fn(_) | ItemKind::InlineMod(_) => false,
            }
        } else {
            false
        }
    }

    fn def_to_sym<'a>(lcx: &LoweringContext, def: &Def) -> Symbol {
        match def {
            Def::Def(def) => Self::sym_of_item(&lcx.items[*def]),
            Def::Local(local) => lcx.locals[*local].name,
        }
    }

    fn def_to_doc(lcx: &LoweringContext, def: &Def) -> Doc {
        Doc::text(Self::def_to_sym(lcx, def).as_str())
    }
}
