use ayuc_hir::{BinaryOp, Expr, ExprKind, ItemKind, Literal, Stmt, StmtKind};
use ayuc_id::hir::PackageId;
use ayuc_tyctx::TyCtx;
use std::fmt::Write;

pub struct LuauCodegen;

fn write_expr(buf: &mut String, expr: &Expr) {
    match &expr.kind {
        ExprKind::Call(call) => {
            write_expr(buf, &call.callee);

            let _ = write!(buf, "(");

            for (i, x) in call.args.iter().enumerate() {
                write_expr(buf, x);

                if i != call.args.len() - 1 {
                    let _ = write!(buf, ", ");
                }
            }

            let _ = write!(buf, ")");
        }
        ExprKind::Ident(ident) => {
            let _ = write!(buf, "{}", ident.as_str());
        }
        ExprKind::Lit(Literal::Str(str)) => {
            let _ = write!(buf, "\"{}\"", str.as_str());
        }
        ExprKind::Lit(Literal::Integer(value)) => {
            let _ = write!(buf, "{}", value);
        }
        ExprKind::Binary(bin) => {
            write_expr(buf, &bin.left);

            let _ = write!(
                buf,
                " {} ",
                match bin.operator {
                    BinaryOp::Add => "+",
                }
            );

            write_expr(buf, &bin.right);
        }
    }
}

fn write_stmt(buf: &mut String, stmt: &Stmt) {
    match &stmt.kind {
        StmtKind::Expr(expr) => write_expr(buf, expr),
        StmtKind::Let(var_decl) => {
            let _ = write!(buf, "local {} = ", var_decl.ident.as_str());

            write_expr(buf, &var_decl.init);
        }
        StmtKind::Return(ret) => {
            let _ = write!(buf, "return");

            if let Some(expr) = &ret.expr {
                let _ = write!(buf, " ");

                write_expr(buf, expr);
            }
        }
    };

    let _ = writeln!(buf);
}

impl LuauCodegen {
    pub fn emit(module_id: PackageId, ty_ctx: &TyCtx) -> String {
        // this is an experimental version of the codegen which is not intended to be used.

        let mut buf = String::new();
        let mut contains_main = false;
        let module = ty_ctx.package(module_id);

        for item in &module.items {
            match &item.kind {
                ItemKind::Fn(fn_item) => {
                    if fn_item.name.as_str() == "main" {
                        contains_main = true;
                    }

                    let _ = write!(buf, "function {}(", fn_item.name.as_str());

                    for (i, param) in fn_item.params.iter().enumerate() {
                        if i > 0 {
                            let _ = write!(buf, ", {}", param.name.as_str());
                        } else {
                            let _ = write!(buf, "{}", param.name.as_str());
                        }
                    }

                    let _ = writeln!(buf, ")");

                    for stmt in &fn_item.block.stmts {
                        write_stmt(&mut buf, stmt);
                    }

                    let _ = writeln!(buf, "end");
                }
                ItemKind::ExternFn(_) => {}
            }
        }

        if contains_main {
            let _ = writeln!(buf, "return main() -- autogenerated by ayuc");
        }

        buf
    }
}
